"use strict";
let ytPlayer=null,ytPromise=null,mediaToken=0,lastMediaTime=0,lastMediaAt=0,manualAte=0,mediaState="stopped",mediaWarnedAt=0;
function songVideoId(song){return /^[\w-]{11}$/.test(String(song&&song.videoId||""))?String(song.videoId):""}
function mediaFailure(message){mediaState="failed";state.videoPlaying=false;document.body.classList.remove("karaokeToqueNoVideo");stopTickIfIdle();updateControls();notify(`${message} A cifra continua disponível; use Rolar ou Sincro.`)}
async function ensurePlayer(){
  if(ytPlayer)return ytPlayer;if(ytPromise)return ytPromise;
  const host=$("karaokeFrame");host.textContent="";const mount=document.createElement("div");mount.id="ytPlayer";host.appendChild(mount);
  ytPromise=YouTubeAdapter.create(mount,{onState:(value,states)=>{if(value===states.PLAYING){mediaState="playing";state.videoPlaying=true;lastMediaAt=performance.now();document.body.classList.remove("karaokeToqueNoVideo");keepAwake();startTick()}else if(value===states.BUFFERING)mediaState="loading";else if(value===states.ENDED){mediaState="ended";state.videoPlaying=false;notify(state.currentIndex<state.setlist.length-1?"Música encerrada. Toque em Próxima para continuar.":"Fim do repertório.",true)}else{mediaState="paused";state.videoPlaying=false}updateControls()},onError:()=>mediaFailure("Este vídeo não está disponível para reprodução aqui.")}).then(player=>ytPlayer=player).catch(error=>{ytPromise=null;throw error});return ytPromise
}
async function karaokeLoad(id,token){try{const player=await ensurePlayer();if(token!==mediaToken||!state.karaoke)return;mediaState="loading";player.cueVideoById(id);updateControls()}catch(error){if(token===mediaToken)mediaFailure(error.message||"Não foi possível abrir a mídia.")}}
function enterKaraoke(){const id=songVideoId(state.current);if(!id)return notify("Esta música ainda não tem vídeo. Escolha um em Acompanhamento.");if(!navigator.onLine)return notify("A mídia precisa de internet. A cifra e a rolagem continuam funcionando.");stopAll();state.karaoke=true;mediaState="loading";const token=++mediaToken;karaokeLoad(id,token);keepAwake();startTick();updateControls();notify("Acompanhamento pronto. Toque em Tocar quando quiser começar.",true)}
function exitKaraoke(){if(!state.karaoke)return;state.karaoke=false;state.videoPlaying=false;mediaState="stopped";++mediaToken;try{ytPlayer&&ytPlayer.stopVideo()}catch{}document.body.classList.remove("karaokeToqueNoVideo");stopTickIfIdle();releaseAwake();updateControls();applyAutoSpeed()}
function toggleKaraoke(){state.karaoke?exitKaraoke():enterKaraoke()}
function karaokeStop(){if(!state.karaoke)return;try{ytPlayer&&ytPlayer.pauseVideo()}catch{}state.videoPlaying=false;mediaState="paused"}
function karaokePlayPause(){if(!state.karaoke)return;if(!ytPlayer)return notify("A mídia ainda está carregando.");try{if(state.videoPlaying)ytPlayer.pauseVideo();else{ytPlayer.playVideo();setTimeout(()=>{if(state.karaoke&&!state.videoPlaying){document.body.classList.add("karaokeToqueNoVideo");notify("O navegador pediu um toque no próprio vídeo para liberar o som.")}},1500)}}catch{mediaFailure("Não foi possível controlar a mídia.")}}
function karaokeOnSongChange(){if(!state.karaoke)return;const id=songVideoId(state.current);if(!id){exitKaraoke();notify("Esta música não tem mídia. Continue com a cifra, Rolar ou Sincro.");return}const token=++mediaToken;karaokeLoad(id,token)}
function karaokeTime(){if(!ytPlayer||mediaState==="failed")return lastMediaTime;try{const value=Number(ytPlayer.getCurrentTime());if(Number.isFinite(value)){lastMediaTime=value;lastMediaAt=performance.now()}}catch{}return lastMediaTime}
function karaokeLyricTime(){const off=Number(state.current&&state.current.videoOffset)||0;return karaokeTime()-off-(Number(state.audioDelay)||0)/1000}
function karaokeSeek(seconds){if(!state.karaoke||!ytPlayer)return;const target=Math.max(0,Number(seconds)+(Number(state.current&&state.current.videoOffset)||0)+(Number(state.audioDelay)||0)/1000);lastMediaTime=target;try{ytPlayer.seekTo(target,true)}catch{mediaFailure("Não foi possível ajustar o tempo da mídia.")}}
function karaokeScrollPosition(time){if(performance.now()<manualAte)return;const duration=Number(state.current&&state.current.duration)||0;if(duration<=LEAD_IN)return;const distance=scrollDistance();if(distance<=0)return;const progress=Math.max(0,Math.min(1,(time-LEAD_IN)/(duration-LEAD_IN)));$("paperViewport").scrollTop=progress*distance}
function karaokeNudgeOffset(delta){if(!state.current)return;const value=Math.round(((Number(state.current.videoOffset)||0)+delta)*10)/10;state.current.videoOffset=value;rememberSongPref("videoOffset",value);if(typeof updateKaraokeDialogFields==="function")updateKaraokeDialogFields();notify(value===0?"Ajuste desta música zerado.":`Letra ${value>0?"atrasada":"adiantada"} ${Math.abs(value).toFixed(1)}s.`,true)}
function karaokeNudgeDelay(deltaMs){const value=Math.max(0,Math.min(500,Math.round((Number(state.audioDelay)||0)+deltaMs)));state.audioDelay=value;updatePrefsSoon();if(typeof updateKaraokeDialogFields==="function")updateKaraokeDialogFields();notify(`Atraso da caixa Bluetooth: ${value} ms.`,true)}
function karaokeWatchdog(){if(!state.karaoke||!state.videoPlaying)return;const before=lastMediaTime,time=karaokeTime();if(time>before||performance.now()-lastMediaAt<2500)return;if(performance.now()-mediaWarnedAt<10000)return;mediaWarnedAt=performance.now();state.videoPlaying=false;mediaState="paused";updateControls();notify("A mídia parou de informar o tempo. A letra foi pausada; toque em Tocar para retomar.")}
function parseVideoId(text){const value=String(text||"").trim();if(/^[\w-]{11}$/.test(value))return value;let url;try{url=new URL(value.startsWith("http")?value:"https://"+value)}catch{return""}if(!/(^|\.)(youtube\.com|youtube-nocookie\.com|youtu\.be)$/.test(url.hostname))return"";if(url.hostname.endsWith("youtu.be"))return(url.pathname.split("/")[1]||"").slice(0,11);const id=url.searchParams.get("v");if(id)return id.slice(0,11);const match=url.pathname.match(/\/(embed|shorts|live|v)\/([\w-]{11})/);return match?match[2]:""}
async function fetchVideoTitle(id){const response=await fetchSafe(`https://www.youtube.com/oembed?url=${encodeURIComponent("https://www.youtube.com/watch?v="+id)}&format=json`,{headers:{Accept:"application/json"}},8000);if(!response.ok)throw Error(response.status===401||response.status===404?"Vídeo não encontrado, particular ou removido.":"Não consegui confirmar esse vídeo.");const data=await response.json();return{title:String(data.title||""),author:String(data.author_name||"")}}
function youtubeSearchUrl(song){return"https://www.youtube.com/results?search_query="+encodeURIComponent(`${song&&song.artist||""} ${song&&song.title||""} karaokê`.trim())}
