"use strict";
/* Editar letra e tempos de uma música já aberta. */
const EDIT_LRC_TIME=/\[(\d+):(\d+(?:[.:]\d+)?)\]/g;
let timingRows=[],draftTimer=null;
function formatLrcTime(seconds){const total=Math.max(0,Math.round(Number(seconds)*100)/100),minutes=Math.floor(total/60),rest=(total-minutes*60).toFixed(2).padStart(5,"0");return "["+String(minutes).padStart(2,"0")+":"+rest+"]"}
function lrcTimingRows(text){const rows=[];text.split(/\r?\n/).forEach((line,lineIndex)=>{const marks=[...line.matchAll(EDIT_LRC_TIME)];if(!marks.length)return;const body=line.replace(EDIT_LRC_TIME,"").replace(/\[[a-z]{2,10}:[^\]]*\]/gi,"").trim();marks.forEach((mark,markIndex)=>rows.push({line:lineIndex,mark:markIndex,time:+mark[1]*60+parseFloat(mark[2].replace(":",".")),text:body||"(trecho sem texto)"}))});return rows}
async function autosaveSongDraft(){const current=state.current,id=current&&current.entryId,owner=current&&current.ownerSetlistId,text=$("editText").value;if(!id)return;await saveDraft(id,{text,title:$("editTitle").value,artist:$("editArtist").value});if(!text.trim()||!owner||!state.current||state.current.entryId!==id)return;const sync=hasLRC(text),fields={title:$("editTitle").value.trim()||current.title,artist:$("editArtist").value.trim(),lyrics:sync?"":text,synced:sync?text:"",contentRevision:(current.contentRevision||1)+1};Object.assign(current,fields);if(updateEntrySetting(owner,id,fields))await saveSetlists()}
function applyLrcTimings(text,rows){const byLine=new Map();rows.forEach(row=>{if(!byLine.has(row.line))byLine.set(row.line,[]);byLine.get(row.line).push(row)});return text.split(/\r?\n/).map((line,lineIndex)=>{const changes=byLine.get(lineIndex)||[],marks=[...line.matchAll(EDIT_LRC_TIME)];for(let k=marks.length-1;k>=0;k--){const row=changes.find(item=>item.mark===k);if(!row)continue;const replacement=formatLrcTime(row.time);line=line.slice(0,marks[k].index)+replacement+line.slice(marks[k].index+marks[k][0].length)}return line}).join("\n")}
async function openSongEditor(){if(!state.current)return notify("Abra uma música antes de editar.");$("editTitle").value=state.current.title||"";$("editArtist").value=state.current.artist||"";$("editText").value=state.current.synced||state.current.lyrics||"";try{const draft=state.current.entryId&&await loadDraft(state.current.entryId);if(draft&&draft.value&&draft.value.text!==$("editText").value){$("editText").value=draft.value.text;notify("Recuperei uma edição que ainda não tinha sido salva.",true)}}catch{}$("timingOpenBtn").hidden=!hasLRC($("editText").value);$("editDialog").showModal()}
function openTimingEditor(){const rows=lrcTimingRows($("editText").value);if(!rows.length)return notify("Inclua marcas como [00:12.30] antes de ajustar os tempos.");timingRows=rows;const list=$("timingRows");list.innerHTML="";rows.forEach((row,index)=>{const item=document.createElement("div");item.className="timingRow";const input=document.createElement("input");input.type="number";input.min="0";input.step="0.01";input.value=row.time.toFixed(2);input.dataset.row=index;input.setAttribute("aria-label","Tempo do trecho "+(index+1));const text=document.createElement("span");text.className="timingText";text.textContent=row.text;const label=document.createElement("span");label.className="timingLabel";label.textContent="Trecho "+(index+1);item.append(input,label,text);list.append(item)});$("timingDialog").showModal()}
$("timingOpenBtn").addEventListener("click",openTimingEditor);for(const field of ["editText","editTitle","editArtist"])$(field).addEventListener("input",()=>{if(field==="editText")$("timingOpenBtn").hidden=!hasLRC($("editText").value);clearTimeout(draftTimer);if(state.current&&state.current.entryId)draftTimer=setTimeout(()=>autosaveSongDraft().catch(()=>showSaveState("error","Não foi possível salvar o rascunho")),300)});$("timingForm").addEventListener("submit",event=>{if(event.submitter?.value==="cancel")return;event.preventDefault();const inputs=[...$("timingRows").querySelectorAll("input")];for(const input of inputs){const value=Number(input.value);if(!Number.isFinite(value)||value<0)return notify("Cada tempo precisa ser um número igual ou maior que zero.");timingRows[Number(input.dataset.row)].time=value}$("editText").value=applyLrcTimings($("editText").value,timingRows);$("timingDialog").close();notify("Tempos atualizados no editor. Clique em Salvar letra para gravar.",true)});
function saveSongEdit(){clearTimeout(draftTimer);if(!state.current)return;const texto=$("editText").value;if(!texto.trim())return notify("A letra não pode ficar vazia.");const sync=hasLRC(texto),owner=state.current.ownerSetlistId,entryId=state.current.entryId;state.current.title=$("editTitle").value.trim()||state.current.title;state.current.artist=$("editArtist").value.trim();state.current.lyrics=sync?"":texto;state.current.synced=sync?texto:"";state.current.contentRevision=(state.current.contentRevision||1)+1;if(owner&&entryId&&updateEntrySetting(owner,entryId,storedSong(state.current)))saveSetlists();$("songTitle").textContent=state.current.title||"Sem título";$("songArtist").textContent=(state.current.artist||"SEM ARTISTA").toUpperCase();stopAll();renderCurrentLyrics();renderList();updateSaveButton();$("editDialog").close();deleteDraft(entryId).catch(()=>{});notify("Letra atualizada.",true)}
