"use strict";
$("searchForm").onsubmit=async e=>{e.preventDefault();const q=$("searchInput").value.trim();if(!q)return;notify("Procurando…",true);try{state.results=await searchMusic(q);state.tab="results";renderList();if(!state.results.length)notify("Nada encontrado. Tente artista e música juntos ou troque a fonte.");else if(state.source!=="lrclib"&&!state.keyVag)notify("Resultados encontrados. Para abrir a letra do Vagalume, configure sua chave em Fontes.");else notify("")}catch(err){state.results=[];renderList();notify(navigator.onLine?`Falha na busca: ${esc(err.message)}`:"Você está offline. O repertório salvo continua funcionando.")}};
document.querySelectorAll(".chip").forEach(b=>b.onclick=()=>{state.source=b.dataset.source;document.querySelectorAll(".chip").forEach(x=>x.classList.toggle("active",x===b));$("searchInput").placeholder=state.source==="excerpt"?"Um trecho da letra":state.source==="lrclib"?"Música, artista ou álbum":"Artista e música";updatePrefs();if($("searchInput").value.trim())$("searchForm").requestSubmit()});
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;renderList()});
$("menuBtn").onclick=()=>$("sidebar").classList.toggle("open");$("saveBtn").onclick=addSong;$("prevBtn").onclick=()=>jumpSong(-1);$("nextBtn").onclick=()=>jumpSong(1);$("topBtn").onclick=()=>$("paperViewport").scrollTo({top:0,behavior:"smooth"});$("scrollBtn").onclick=toggleScroll;$("syncBtn").onclick=toggleSync;
document.querySelectorAll("[data-speed]").forEach(b=>b.onclick=()=>{state.speed=Math.max(4,Math.min(140,state.speed+Number(b.dataset.speed)));updateControls();updatePrefs()});document.querySelectorAll("[data-font]").forEach(b=>b.onclick=()=>{state.font=Math.max(16,Math.min(72,state.font+Number(b.dataset.font)));updateControls();updatePrefs()});document.querySelectorAll("[data-key]").forEach(b=>b.onclick=()=>{state.key=Math.max(-11,Math.min(11,state.key+Number(b.dataset.key)));$("keyOut").textContent=(state.key>0?"+":"")+state.key;$("paper").querySelectorAll(".chord").forEach(n=>n.textContent=transposeLine(state.lines[+n.dataset.i].text,state.key))});
$("stageBtn").onclick=()=>{state.stage=!state.stage;if(state.stage)keepAwake();updateControls();updatePrefs()};$("fullscreenBtn").onclick=fullscreen;$("pasteBtn").onclick=()=>$("pasteDialog").showModal();$("sourcesBtn").onclick=()=>{$("vagalumeKey").value=state.keyVag;$("sourcesDialog").showModal()};$("helpBtn").onclick=()=>$("helpDialog").showModal();
$("pasteForm").addEventListener("submit",e=>{if(e.submitter?.value==="cancel")return;const text=$("pasteText").value;if(!text.trim()){e.preventDefault();return $("pasteText").focus()}const sync=hasLRC(text);openSong({title:$("pasteTitle").value.trim()||"Letra colada",artist:$("pasteArtist").value.trim(),lyrics:sync?"":text,synced:sync?text:"",source:"colado"});$("pasteDialog").close();e.preventDefault()});
$("sourcesForm").addEventListener("submit",e=>{if(e.submitter?.value==="cancel")return;state.keyVag=$("vagalumeKey").value.trim();updatePrefs();$("sourcesDialog").close();notify(state.keyVag?"Chave salva neste aparelho.":"Chave removida.",true);e.preventDefault()});
$("exportBtn").onclick=exportSetlist;$("importBtn").onclick=()=>$("importFile").click();$("importFile").onchange=e=>{if(e.target.files[0])importSetlist(e.target.files[0]);e.target.value=""};
window.addEventListener("online",updateNetwork);window.addEventListener("offline",updateNetwork);document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible"&&(state.stage||state.scrolling||state.syncing))keepAwake()});
document.addEventListener("keydown",e=>{if(/^(INPUT|TEXTAREA|SELECT)$/.test(e.target.tagName)||document.querySelector("dialog[open]"))return;switch(e.key){case" ":e.preventDefault();if(e.shiftKey&&state.lrc.length)toggleSync();else toggleScroll();break;case"ArrowUp":e.preventDefault();state.speed=Math.min(140,state.speed+2);updateControls();updatePrefs();break;case"ArrowDown":e.preventDefault();state.speed=Math.max(4,state.speed-2);updateControls();updatePrefs();break;case"ArrowLeft":jumpSong(-1);break;case"ArrowRight":jumpSong(1);break;case"PageDown":e.preventDefault();$("paperViewport").scrollBy({top:$("paperViewport").clientHeight*.5,behavior:"smooth"});break;case"PageUp":e.preventDefault();$("paperViewport").scrollBy({top:-$("paperViewport").clientHeight*.5,behavior:"smooth"});break;case"p":case"P":$("stageBtn").click();break;case"f":case"F":fullscreen();break;case"Escape":stopAll();break}});
$("paperViewport").addEventListener("pointerdown",()=>{if(state.scrolling)toggleScroll()});

(function init(){const oldP=load("estante:preferencias",{}),p=load(KEYS.prefs,null)||{source:oldP.fonte,speed:oldP.velocidade,font:oldP.corpo,stage:oldP.palco,keyVag:oldP.chaveVagalume};const raw=load(KEYS.setlist,null)||load("estante:repertorio",[]);state.setlist=(raw||[]).map(normalizeSong);state.source=(p.source==="trecho"?"excerpt":p.source)||"lrclib";state.speed=p.speed||18;state.font=p.font||26;state.stage=!!p.stage;state.keyVag=p.keyVag||"";save(KEYS.setlist,state.setlist);document.querySelectorAll(".chip").forEach(b=>b.classList.toggle("active",b.dataset.source===state.source));$("searchInput").placeholder=state.source==="excerpt"?"Um trecho da letra":state.source==="lrclib"?"Música, artista ou álbum":"Artista e música";updateControls();updateNetwork();renderList();updateSaveButton();$("searchInput").focus()})();
