import { type Data, type Member, today, permissions } from "./model.ts";
import { addDays } from "./home.ts";
export const ADMIN = "00000000-0000-4000-8000-000000000001",
  MEMBER = "00000000-0000-4000-8000-000000000002",
  HOME = "00000000-0000-4000-8000-000000000003";
export function demoData(): Data {
  const date = today(),
    m = date.slice(0, 7);
  const base = { home_id: HOME, owner_id: ADMIN, shared: false };
  return {
    home: {
      id: HOME,
      name: "Nossa casa",
      owner_id: ADMIN,
      budget_cents: 450000,
    },
    members: [
      {
        home_id: HOME,
        user_id: ADMIN,
        display_name: "Administrador",
        role: "admin",
        active: true,
        permissions: Object.fromEntries(
          Object.keys(permissions).map((k) => [k, true]),
        ) as Member["permissions"],
        password_change_required: false,
      },
      {
        home_id: HOME,
        user_id: MEMBER,
        display_name: "Esposa",
        role: "member",
        active: true,
        permissions: Object.fromEntries(
          Object.keys(permissions).map((k) => [k, true]),
        ) as Member["permissions"],
        password_change_required: false,
      },
    ],
    accounts: [
      {
        ...base,
        id: "demo-account",
        name: "Conta pessoal",
        area: "personal",
        opening_cents: 820000,
        balance_date: `${m}-01`,
      },
    ],
    cards: [
      {
        ...base,
        id: "demo-card",
        name: "Meu cartão",
        limit_cents: 600000,
        closing_day: 10,
        due_day: 17,
      },
      {
        ...base,
        id: "demo-wife-card",
        owner_id: MEMBER,
        name: "Cartão da esposa",
        limit_cents: 300000,
        closing_day: 15,
        due_day: 22,
      },
    ],
    entries: [
      {
        ...base,
        id: "demo-income",
        description: "Renda do mês",
        amount_cents: 650000,
        date,
        kind: "income",
        category: "Salário",
        area: "personal",
        status: "paid",
        payment: "cash",
        account_id: "demo-account",
        card_id: null,
        target_account_id: null,
        debt_id: null,
        installments: 1,
        invoice_month: null,
        due_date: null,
        source_ref: null,
      },
      {
        ...base,
        id: "demo-rent",
        description: "Aluguel da casa",
        shared: true,
        amount_cents: 165000,
        date,
        kind: "expense",
        category: "Moradia",
        area: "household",
        status: "paid",
        payment: "cash",
        account_id: "demo-account",
        card_id: null,
        target_account_id: null,
        debt_id: null,
        installments: 1,
        invoice_month: null,
        due_date: null,
        source_ref: null,
      },
      {
        ...base,
        id: "demo-grocery",
        owner_id: MEMBER,
        description: "Compras da semana",
        amount_cents: 38750,
        date,
        kind: "expense",
        category: "Mercado",
        area: "household",
        status: "paid",
        payment: "card",
        card_id: "demo-wife-card",
        account_id: null,
        target_account_id: null,
        debt_id: null,
        installments: 1,
        invoice_month: null,
        due_date: null,
        source_ref: null,
      },
      {
        ...base,
        id: "demo-energy",
        description: "Energia elétrica",
        shared: true,
        amount_cents: 18990,
        date,
        kind: "expense",
        category: "Moradia",
        area: "household",
        status: "pending",
        payment: "cash",
        account_id: null,
        card_id: null,
        target_account_id: null,
        debt_id: null,
        installments: 1,
        invoice_month: null,
        due_date: `${m}-01`,
        source_ref: null,
      },
      {
        ...base,
        id: "demo-private",
        description: "Curso de desenvolvimento",
        amount_cents: 89000,
        date,
        kind: "expense",
        category: "Educação",
        area: "personal",
        status: "paid",
        payment: "card",
        card_id: "demo-card",
        account_id: null,
        target_account_id: null,
        debt_id: null,
        installments: 3,
        invoice_month: null,
        due_date: null,
        source_ref: null,
      },
    ],
    debts: [],
    goals: [
      {
        ...base,
        id: "demo-goal",
        name: "Reserva de emergência",
        shared: true,
        target_cents: 1500000,
        saved_cents: 420000,
        due_date: null,
      },
    ],
    pantry: [
      {
        id: "demo-rice",
        home_id: HOME,
        name: "Arroz",
        unit: "kg",
        quantity: 1.2,
        minimum: 2,
        daily_use: 0.15,
        price_cents: 650,
        expires_on: null,
        updated_at: new Date().toISOString(),
        location: "kitchen",
      },
      {
        id: "demo-milk",
        home_id: HOME,
        name: "Leite",
        unit: "litro",
        quantity: 2,
        minimum: 3,
        daily_use: 0.5,
        price_cents: 599,
        expires_on: date,
        updated_at: new Date().toISOString(),
        location: "fridge",
      },
      {
        id: "demo-coffee",
        home_id: HOME,
        name: "Café",
        unit: "pacote",
        quantity: 3,
        minimum: 1,
        daily_use: 0.1,
        price_cents: 1690,
        expires_on: null,
        updated_at: new Date().toISOString(),
        location: "kitchen",
      },
      {
        id: "demo-soap",
        home_id: HOME,
        name: "Sabão em pó",
        unit: "caixa",
        quantity: 1,
        minimum: 1,
        daily_use: 0.0333,
        price_cents: 2290,
        expires_on: null,
        updated_at: new Date().toISOString(),
        location: "cleaning",
      },
    ],
    shopping: [],
    documents: [],
    audit: [],
    recurring: [],
    tasks: [
      { id: "demo-task-trash", home_id: HOME, title: "Tirar o lixo", notes: "", kind: "cleaning", assignee_id: MEMBER,
        due_date: date, repeat: "daily", done_at: null, done_by: null, previous_id: null, created_by: ADMIN, created_at: `${date}T08:00:00Z` },
      { id: "demo-task-bath", home_id: HOME, title: "Limpar o banheiro", notes: "Inclui trocar as toalhas.", kind: "cleaning", assignee_id: ADMIN,
        due_date: addDays(date, -1), repeat: "weekly", done_at: null, done_by: null, previous_id: null, created_by: ADMIN, created_at: `${date}T08:00:00Z` },
      { id: "demo-task-filter", home_id: HOME, title: "Trocar o filtro de água", notes: "", kind: "maintenance", assignee_id: null,
        due_date: addDays(date, 10), repeat: "none", done_at: null, done_by: null, previous_id: null, created_by: ADMIN, created_at: `${date}T08:00:00Z` },
    ],
    catalog: [
      // Oferta fictícia só da demonstração, para mostrar como os encartes aparecem.
      { id: "demo-offer", home_id: HOME, name: "Arroz", brand: "Camil", size: "5 kg", unit: "pacote", category: "mercearia",
        store: "Atacadão", price_cents: 2490, offer_until: addDays(date, 7), created_by: ADMIN, created_at: `${date}T08:00:00Z` },
    ],
    pantryEvents: [
      { id: "demo-loss", home_id: HOME, pantry_id: "demo-milk", name: "Leite", kind: "lost", quantity: 1, value_cents: 599,
        actor_id: MEMBER, created_at: new Date().toISOString() },
    ],
  };
}
