import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import test from 'node:test';
const A='00000000-0000-4000-8000-000000000001', B='00000000-0000-4000-8000-000000000002', H='00000000-0000-4000-8000-000000000003';
test('personal preferences: ownership, suspension, server revision and stale-device conflict', async t => {
 const db=new PGlite(); t.after(()=>db.close());
 await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;grant usage on schema auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;grant usage on schema storage to authenticated;grant select,insert,delete on storage.objects to authenticated;`);
 for(const file of ['20261004024051_family_app.sql','20261005055306_family_preferences.sql']) await db.exec(readFileSync(new URL('../supabase/migrations/'+file,import.meta.url),'utf8'));
 await db.exec(`insert into auth.users values('${A}'),('${B}');insert into fin_homes(id,name,owner_id) values('${H}','Synthetic home','${A}');insert into fin_members(home_id,user_id,display_name,role) values('${H}','${A}','Admin','admin'),('${H}','${B}','Member','member');`);
 const asUser=async id=>db.exec(`reset role;set request.jwt.claim.sub='${id}';set role authenticated;`);
 await asUser(B);
 await db.exec(`insert into fin_preferences(user_id,theme) values('${B}','dark')`);
 await assert.rejects(db.exec(`insert into fin_preferences(user_id) values('${A}')`));
 await assert.rejects(db.exec(`update fin_preferences set user_id='${A}' where user_id='${B}'`));
 await assert.rejects(db.exec(`update fin_preferences set revision=100 where user_id='${B}'`));
 await assert.rejects(db.exec(`update fin_preferences set dashboard_order=array['private-record'] where user_id='${B}'`));
 const saved=await db.query(`update fin_preferences set palette='ocean' where user_id='${B}' and revision=1 returning revision`);
 assert.equal(saved.rows[0].revision,2);
 assert.equal((await db.query(`update fin_preferences set palette='plum' where user_id='${B}' and revision=1 returning revision`)).rows.length,0);
 await asUser(A);
 assert.equal((await db.query(`select * from fin_preferences where user_id='${B}'`)).rows.length,0,'admin must not read member preferences');
 assert.equal((await db.query(`update fin_preferences set theme='light' where user_id='${B}' returning user_id`)).rows.length,0);
 await db.exec(`insert into fin_preferences(user_id) values('${A}')`);
 assert.equal((await db.query('select * from fin_preferences')).rows.length,1);
 await db.exec(`reset role;update fin_members set active=false where user_id='${B}'`);
 await asUser(B);
 assert.equal((await db.query('select * from fin_preferences')).rows.length,0);
 assert.equal((await db.query(`update fin_preferences set theme='light' where user_id='${B}' returning user_id`)).rows.length,0);
 await db.exec('reset role;set role anon');
 await assert.rejects(db.query('select * from fin_preferences'));
});
